services:
  dcbadge:
    #build: .
    restart: unless-stopped
    image: ghcr.io/limesdotpink/dcbadge:main
    ports:
     - '9398:9398'
    env_file: '.env'
  shields:
    image: shieldsio/shields:next
    restart: always
    environment:
     - PORT=8080
    ports:
     - 8080:41053

